# Generated by Django 6.0.6 on 2026-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='description',
            field=models.TextField(),
        ),
    ]
